### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by soyabn09** [LethalEthan/server-setup#15]
`Reccomended` to `Recommended` - https://github.com/LethalEthan/server-setup/blob/main/setup.py#L311

`reccomended` to  `recommended`  - https://github.com/LethalEthan/server-setup/blob/main/setup.py#L540

**Comment by LethalEthan** [comment]
I normally spell it that way, TIL I am spelling it wrong lol. brb just gonna rewrite the dictionary
